source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'ASMessenger_Example' do
  pod "ASMessenger", :path => "../"
end

target 'ASMessenger_Tests' do
  pod "ASMessenger", :path => "../"

end
